[package]
name = "json_mtg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
opt-level = 3

[dependencies]
serde_json = "1.0.91"
regex = "1.7.1"
deunicode = "1.3.3"